[package]
name = "handshake-client-types"
version = "0.1.0"
authors = ["Urkel Labs <engineering@urkel.io>"]
edition = "2018"

[dependencies]

# Unknown External
serde = "1"
serde_derive = "1"
serde_json = "1"
